package ru.inno.earthquakes.model.dbobjects;

import io.objectbox.BoxStore;
import io.objectbox.annotation.Entity;
import io.objectbox.annotation.Generated;
import io.objectbox.annotation.Id;
import io.objectbox.annotation.Relation;
import io.objectbox.annotation.apihint.Internal;
import io.objectbox.relation.ToOne;

/**
 * @author Artur Badretdinov (Gaket)
 *         22.07.17
 */
@Entity
public class EarthquakeWithDist {

    @Id
    private long id;
    @Relation
    Earthquake earthquake ;
    @Relation
    Coordinates currentPosition ;
    private double distance;

    /** Used to resolve relations */
    @Internal
    @Generated(1307364262)
    transient BoxStore __boxStore;
    @Internal
    @Generated(25493401)
    transient ToOne<Earthquake> earthquakeToOne = new ToOne<>(this,
            EarthquakeWithDist_.earthquake);
    @Internal
    @Generated(1153309622)
    transient ToOne<Coordinates> currentPositionToOne = new ToOne<>(this,
            EarthquakeWithDist_.currentPosition);


    @Generated(1810425439)
    public EarthquakeWithDist() {
    }

    @Generated(2041823397)
    @Internal
    /** This constructor was generated by ObjectBox and may change any time. */
    public EarthquakeWithDist(long id, double distance, long earthquakeId,
            long currentPositionId) {
        this.id = id;
        this.distance = distance;
        this.earthquakeToOne.setTargetId(earthquakeId);
        this.currentPositionToOne.setTargetId(currentPositionId);
    }

    public long getId() {
        return id;
    }

    public void setId(long id) {
        this.id = id;
    }

    public double getDistance() {
        return distance;
    }

    public void setDistance(double distance) {
        this.distance = distance;
    }

    /** To-one relationship, resolved on first access. */
    @Generated(325347392)
    public Earthquake getEarthquake() {
        earthquake = earthquakeToOne.getTarget();
        return earthquake;
    }

    /** Set the to-one relation including its ID property. */
    @Generated(1815530238)
    public void setEarthquake(Earthquake earthquake) {
        earthquakeToOne.setTarget(earthquake);
        this.earthquake = earthquake;
    }

    /** To-one relationship, resolved on first access. */
    @Generated(1419447526)
    public Coordinates getCurrentPosition() {
        currentPosition = currentPositionToOne.getTarget();
        return currentPosition;
    }

    /** Set the to-one relation including its ID property. */
    @Generated(82809794)
    public void setCurrentPosition(Coordinates currentPosition) {
        currentPositionToOne.setTarget(currentPosition);
        this.currentPosition = currentPosition;
    }

}
