package ru.inno.earthquakes.model.dbobjects;

import java.util.Date;

import io.objectbox.BoxStore;
import io.objectbox.annotation.Entity;
import io.objectbox.annotation.Generated;
import io.objectbox.annotation.Id;
import io.objectbox.annotation.Relation;
import io.objectbox.annotation.apihint.Internal;
import io.objectbox.relation.ToOne;

/**
 * @author Artur Badretdinov (Gaket)
 *         20.07.17.
 */
@Entity
public class Earthquake {

    @Id
    private long id;

    private String title;
    private Double magnitude;
    private Date time;

    @Relation
    DbLocation location;
    private String detailsUrl;

    /** Used to resolve relations */
    @Internal
    @Generated(1307364262)
    transient BoxStore __boxStore;

    @Internal
    @Generated(1253170607)
    transient ToOne<DbLocation> locationToOne = new ToOne<>(this,
            Earthquake_.location);



    @Generated(886460459)
    public Earthquake() {
    }




    @Generated(1908895655)
    @Internal
    /** This constructor was generated by ObjectBox and may change any time. */
    public Earthquake(long id, String title, Double magnitude, Date time,
            String detailsUrl, long locationId) {
        this.id = id;
        this.title = title;
        this.magnitude = magnitude;
        this.time = time;
        this.detailsUrl = detailsUrl;
        this.locationToOne.setTargetId(locationId);
    }




    public String getTitle() {
        return title;
    }

    public void setTitle(String title) {
        this.title = title;
    }

    public Double getMagnitude() {
        return magnitude;
    }

    public void setMagnitude(Double magnitude) {
        this.magnitude = magnitude;
    }

    public Date getTime() {
        return time;
    }

    public void setTime(Date time) {
        this.time = time;
    }

    public String getDetailsUrl() {
        return detailsUrl;
    }

    public void setDetailsUrl(String url) {
        this.detailsUrl = url;
    }

    public long getId() {
        return id;
    }

    public void setId(long id) {
        this.id = id;
    }




    /** To-one relationship, resolved on first access. */
    @Generated(1366552269)
    public DbLocation getLocation() {
        location = locationToOne.getTarget();
        return location;
    }




    /** Set the to-one relation including its ID property. */
    @Generated(1307289585)
    public void setLocation(DbLocation location) {
        locationToOne.setTarget(location);
        this.location = location;
    }




   
}
